name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: _site 
          publish_branch: prod
          github_token: ${{ secrets.GITHUB_TOKEN }}
